"""empty message

Revision ID: 74efac2f6437
Revises: 
Create Date: 2024-01-25 09:41:22.060498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74efac2f6437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('checked_dt',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('checked_dt',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
