"""empty message

Revision ID: 7cbcbb563ade
Revises: 74efac2f6437
Create Date: 2024-01-25 09:42:55.780776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbcbb563ade'
down_revision = '74efac2f6437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_column('checked_dt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_dt', sa.DATE(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
